[project]
site_name = "Timo Hankamer"
site_url = "https://tibuntu.dev"
site_description = "Cloud Platform Engineer from Oberhausen, Germany"
docs_dir = "docs"
site_dir = "site"

[[project.nav]]
Home = "index.md"

[[project.nav]]
Projects = "projects.md"
